language: php
php:
  - 5.6
  - 7.0
  - 7.1
install:
  - phpize
  - ./configure
  - make
  - make install
script:
  - export NO_INTERACTION=1
  - export REPORT_EXIT_STATUS=1
  - export TEST_PHP_ARGS="--show-diff"
  - make test
