language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
matrix:
  include:
    # `php: ..` in here is just descriptive/for UI, they don't affect installed ver.
    - os: osx
      php: "5.6"
      language: generic
      before_install:
        - brew update && brew tap homebrew/php && brew install php56
    - os: osx
      php: "7.0"
      language: generic
      before_install:
        - brew update && brew tap homebrew/php && brew install php70
    - os: osx
      php: "7.1"
      language: generic
      before_install:
        - brew update && brew tap homebrew/php && brew install php71
    - os: osx
      php: "7.2"
      language: generic
      before_install:
        - brew update && brew tap homebrew/php && brew install php72
install:
  - phpize
  - ./configure
  - make
  - make install
script:
  - export NO_INTERACTION=1
  - export REPORT_EXIT_STATUS=1
  - export TEST_PHP_ARGS="--show-diff"
  - make test
